# Generated by Django 4.1.3 on 2022-11-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0017_auto_20220217_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudevent',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Metadata'),
        ),
    ]
