# Generated by Django 4.2.20 on 2025-08-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0019_alter_crudevent_changed_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudevent',
            name='object_json_repr',
            field=models.TextField(blank=True, default='', verbose_name='Object JSON representation'),
        ),
    ]
