# Generated by Django 4.1.3 on 2022-11-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_testbigintforeignkey_testbigintm2m_testbigintmodel_testuuidforeignkey_testuuidm2m_testuuidmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMetadataAModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='metadata A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestMetadataBModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='metadata B', max_length=50)),
                ('model_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.testmetadataamodel')),
            ],
        ),
        migrations.CreateModel(
            name='TestMetadataCModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='metadata C', max_length=50)),
                ('model_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.testmetadatabmodel')),
            ],
        ),
    ]
